@merchant1 = Merchant.create!(name: 'Acedemy Records')
@merchant2 = Merchant.create!(name: 'Brooklyn Record Exchange')

@item_1 = Item.create!(name: "Guerrilla Warfare", description: "Hot Boys 1999", unit_price: 10, merchant_id: @merchant1.id, status: 1)
@item_2 = Item.create!(name: "E.L.E. (Extinction Level Event): The Final World Front", description: "Busta Rhymes 1998", unit_price: 8, merchant_id: @merchant1.id)
@item_3 = Item.create!(name: "Enter the Wu-Tang (36 Chambers)", description: "Wu-Tang Clan 1993", unit_price: 5, merchant_id: @merchant1.id)
@item_4 = Item.create!(name: "Ready to Die", description: "The Notorious B.I.G. 1994", unit_price: 1, merchant_id: @merchant1.id)
@item_7 = Item.create!(name: "Doggstyle", description: "Snoop Doggy Dogg 1993", unit_price: 3, merchant_id: @merchant1.id)
@item_8 = Item.create!(name: "The Miseducation of Lauryn Hill", description: "Lauryn Hill 1998", unit_price: 5, merchant_id: @merchant1.id)

@item_5 = Item.create!(name: "Me Against the World", description: "2Pac 1995", unit_price: 200, merchant_id: @merchant2.id)
@item_6 = Item.create!(name: "Life After Death", description: "The Notorious B.I.G. 1997", unit_price: 300, merchant_id: @merchant2.id)

@customer_1 = Customer.create!(first_name: 'Dee', last_name: 'JJ')
@customer_2 = Customer.create!(first_name: 'Kim', last_name: 'Blake')
@customer_3 = Customer.create!(first_name: 'Dane', last_name: 'Caroline')
@customer_4 = Customer.create!(first_name: 'Gunnar', last_name: 'Bunner')
@customer_5 = Customer.create!(first_name: 'Suzie', last_name: 'Gertie')
@customer_6 = Customer.create!(first_name: 'Caleb', last_name: 'Mark')

@invoice_1 = Invoice.create!(customer_id: @customer_1.id, status: 2, created_at: "2012-03-27 14:54:09")
@invoice_2 = Invoice.create!(customer_id: @customer_1.id, status: 2, created_at: "2012-03-28 14:54:09")
@invoice_3 = Invoice.create!(customer_id: @customer_2.id, status: 2)
@invoice_4 = Invoice.create!(customer_id: @customer_3.id, status: 2)
@invoice_5 = Invoice.create!(customer_id: @customer_4.id, status: 2)
@invoice_6 = Invoice.create!(customer_id: @customer_5.id, status: 2)
@invoice_7 = Invoice.create!(customer_id: @customer_6.id, status: 2)

@invoice_8 = Invoice.create!(customer_id: @customer_6.id, status: 1)

@ii_1 = InvoiceItem.create!(invoice_id: @invoice_1.id, item_id: @item_1.id, quantity: 9, unit_price: 10, status: 2)
@ii_2 = InvoiceItem.create!(invoice_id: @invoice_2.id, item_id: @item_1.id, quantity: 1, unit_price: 10, status: 2)
@ii_3 = InvoiceItem.create!(invoice_id: @invoice_3.id, item_id: @item_2.id, quantity: 2, unit_price: 8, status: 2)
@ii_4 = InvoiceItem.create!(invoice_id: @invoice_4.id, item_id: @item_3.id, quantity: 3, unit_price: 5, status: 1)
@ii_6 = InvoiceItem.create!(invoice_id: @invoice_5.id, item_id: @item_4.id, quantity: 1, unit_price: 1, status: 1)
@ii_7 = InvoiceItem.create!(invoice_id: @invoice_6.id, item_id: @item_7.id, quantity: 1, unit_price: 3, status: 1)
@ii_8 = InvoiceItem.create!(invoice_id: @invoice_7.id, item_id: @item_8.id, quantity: 1, unit_price: 5, status: 1)
@ii_9 = InvoiceItem.create!(invoice_id: @invoice_7.id, item_id: @item_4.id, quantity: 1, unit_price: 1, status: 1)
@ii_10 = InvoiceItem.create!(invoice_id: @invoice_8.id, item_id: @item_5.id, quantity: 1, unit_price: 1, status: 1)
@ii_11 = InvoiceItem.create!(invoice_id: @invoice_1.id, item_id: @item_8.id, quantity: 12, unit_price: 6, status: 1)

@transaction1 = Transaction.create!(credit_card_number: 203942, result: 1, invoice_id: @invoice_1.id)
@transaction2 = Transaction.create!(credit_card_number: 230948, result: 1, invoice_id: @invoice_2.id)
@transaction3 = Transaction.create!(credit_card_number: 234092, result: 1, invoice_id: @invoice_3.id)
@transaction4 = Transaction.create!(credit_card_number: 230429, result: 1, invoice_id: @invoice_4.id)
@transaction5 = Transaction.create!(credit_card_number: 102938, result: 1, invoice_id: @invoice_5.id)
@transaction6 = Transaction.create!(credit_card_number: 879799, result: 0, invoice_id: @invoice_6.id)
@transaction7 = Transaction.create!(credit_card_number: 203942, result: 1, invoice_id: @invoice_7.id)
@transaction8 = Transaction.create!(credit_card_number: 203942, result: 1, invoice_id: @invoice_8.id)

discount_1 = @merchant1.discounts.create!(percent: 20, quantity_threshold: 10)
discount_2 = @merchant1.discounts.create!(percent: 30, quantity_threshold: 15)
discount_3 = @merchant2.discounts.create!(percent: 15, quantity_threshold: 5)
